services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 8FUZs2fV2Mc$
      MYSQL_DATABASE: library_db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - backend-network
    ports:
      - "3306:3306"

networks:
  backend-network:
