services:
  db:
    image: mysql:8.0
    restart: always
    container_name: book-manager-db
    environment:
      MYSQL_ROOT_PASSWORD: 8FUZs2fV2Mc$
      MYSQL_DATABASE: library_db
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  app:
    build: .  # Build from Dockerfile
    container_name: book-manager-app
    ports:
      - 8080:8080  # Map to Spring Boot's default port

    restart: on-failure
    depends_on:
      - db  # Ensure database starts first
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/library_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 8FUZs2fV2Mc$
    volumes:
      - logs:/app/logs  # Persist application logs
    #command: ["/wait-for-script.sh", "db:3306", "java", "-jar", "target/book-manager-app-0.0.1-SNAPSHOT.jar"]

volumes:
  logs:
