name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - main  # Or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install  

    - name: Run Tests
      run: mvn test
